import React from 'react';
import { Modal, Button, Card, Row, Col, Space, Typography, Tag, message } from 'antd';
import { 
  ExportOutlined, 
  CodeOutlined, 
  FileExcelOutlined, 
  FileTextOutlined, 
  PictureOutlined,
  DownloadOutlined,
  CopyOutlined,
  BuildOutlined
} from '@ant-design/icons';
import { useGraphStore } from '../store/graphStore';
import { generateNetworkBOQ, generateCableSchedule } from '@omniflow/network-engine';

const { Paragraph } = Typography;

export const ExportCenterModal: React.FC = () => {
  const {
    graph,
    currentProjectName,
    isExportCenterModalOpen,
    closeExportCenterModal
  } = useGraphStore();

  if (!isExportCenterModalOpen) return null;

  const downloadFile = (filename: string, content: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    message.success(`Downloaded ${filename}`);
  };

  const copyToClipboard = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    message.success(`Copied ${label} to clipboard`);
  };

  // 1. CANONICAL ENGINEERING GRAPH JSON
  const handleExportJson = (download: boolean) => {
    const jsonString = JSON.stringify(graph, null, 2);
    if (download) {
      downloadFile(`${graph.designId || 'engineering_design'}_v${graph.metadata?.version || '1.0'}.json`, jsonString, 'application/json');
    } else {
      copyToClipboard(jsonString, 'Engineering JSON');
    }
  };

  // 2. BOQ CSV
  const handleExportBOQ = (download: boolean) => {
    const boq = generateNetworkBOQ(graph);
    const headers = ['Item Description', 'Category', 'Part Number', 'Quantity', 'Unit Material ($)', 'Unit Labor ($)', 'Total Cost ($)'];
    const rows = boq.items.map(item => [
      `"${item.description.replace(/"/g, '""')}"`,
      `"${item.category}"`,
      `"${item.partNumber}"`,
      item.quantity,
      item.unitCost.toFixed(2),
      item.unitLabour.toFixed(2),
      item.totalCost.toFixed(2)
    ]);
    const csvContent = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');

    if (download) {
      downloadFile(`${graph.designId || 'design'}_BOQ.csv`, csvContent, 'text/csv');
    } else {
      copyToClipboard(csvContent, 'BOQ CSV');
    }
  };

  // 3. CABLE SCHEDULE CSV
  const handleExportCableSchedule = (download: boolean) => {
    const schedule = generateCableSchedule(graph);
    const headers = ['Cable ID', 'Cable Type', 'Source Device', 'Source Port', 'Target Device', 'Target Port', 'Length (m)'];
    const rows = schedule.map(run => [
      run.cableId,
      run.cableType,
      `"${run.sourceDevice.replace(/"/g, '""')}"`,
      run.sourcePort,
      `"${run.targetDevice.replace(/"/g, '""')}"`,
      run.targetPort,
      run.lengthMeters
    ]);
    const csvContent = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');

    if (download) {
      downloadFile(`${graph.designId || 'design'}_CableSchedule.csv`, csvContent, 'text/csv');
    } else {
      copyToClipboard(csvContent, 'Cable Schedule CSV');
    }
  };

  // 4. STANDALONE VECTOR SVG SCHEMATIC
  const handleExportSVG = (download: boolean) => {
    const nodes = Object.values(graph.nodes);
    const connections = Object.values(graph.connections);

    let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
    nodes.forEach(n => {
      minX = Math.min(minX, n.position.x);
      minY = Math.min(minY, n.position.y);
      maxX = Math.max(maxX, n.position.x + 220);
      maxY = Math.max(maxY, n.position.y + 120);
    });
    if (nodes.length === 0) { minX = 0; minY = 0; maxX = 1200; maxY = 800; }

    const width = Math.max(1000, maxX - minX + 160);
    const height = Math.max(700, maxY - minY + 160);

    const svgContent = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="${minX - 80} ${minY - 80} ${width} ${height}" width="${width}" height="${height}" style="background-color: #0b111e; font-family: sans-serif;">
  <defs>
    <filter id="card-shadow" x="-10%" y="-10%" width="120%" height="120%">
      <feDropShadow dx="0" dy="4" stdDeviation="6" flood-color="#000000" flood-opacity="0.5"/>
    </filter>
  </defs>

  <!-- Title Block -->
  <text x="${minX - 40}" y="${minY - 40}" fill="#f8fafc" font-size="20" font-weight="bold">${currentProjectName || 'Engineering System Blueprint'}</text>
  <text x="${minX - 40}" y="${minY - 18}" fill="#94a3b8" font-size="12">Generated by NexFlow Engineering Platform • Standard CAD Schematic</text>

  <!-- Cable Paths -->
  <g id="cables">
    ${connections.map(c => {
      const src = graph.nodes[c.sourceComponentId];
      const tgt = graph.nodes[c.targetComponentId];
      if (!src || !tgt) return '';
      const sx = src.position.x + 200;
      const sy = src.position.y + 40;
      const tx = tgt.position.x;
      const ty = tgt.position.y + 40;
      const color = c.connectionType.includes('POWER') ? '#eab308' : c.connectionType.includes('PIPE') ? '#0284c7' : '#38bdf8';
      return `<path d="M ${sx} ${sy} C ${sx + 80} ${sy}, ${tx - 80} ${ty}, ${tx} ${ty}" fill="none" stroke="${color}" stroke-width="2.5" />
      <circle cx="${(sx + tx)/2}" cy="${(sy + ty)/2}" r="12" fill="#090d16" stroke="${color}" stroke-width="1.2"/>
      <text x="${(sx + tx)/2}" y="${(sy + ty)/2 + 3}" fill="#cbd5e1" font-size="8" text-anchor="middle" font-family="monospace">${c.lengthMeters}m</text>`;
    }).join('\n')}
  </g>

  <!-- Component Nodes -->
  <g id="components">
    ${nodes.map(n => {
      return `<g transform="translate(${n.position.x}, ${n.position.y})" filter="url(#card-shadow)">
        <rect width="200" height="75" rx="8" fill="#0f172a" stroke="#334155" stroke-width="1.5" />
        <rect width="200" height="22" rx="8" fill="#1e293b" />
        <text x="12" y="15" fill="#38bdf8" font-size="10" font-weight="bold">${n.tag}</text>
        <text x="12" y="42" fill="#f8fafc" font-size="11" font-weight="600">${n.name}</text>
        <text x="12" y="60" fill="#94a3b8" font-size="9" font-family="monospace">${n.properties.ipAddress || n.properties.voltage || n.type}</text>
      </g>`;
    }).join('\n')}
  </g>
</svg>`;

    if (download) {
      downloadFile(`${graph.designId || 'design'}_Schematic.svg`, svgContent, 'image/svg+xml');
    } else {
      copyToClipboard(svgContent, 'SVG Vector Schematic');
    }
  };

  // 5. TECHNICAL MARKDOWN SPECIFICATION
  const handleExportMarkdown = (download: boolean) => {
    const nodes = Object.values(graph.nodes);
    const connections = Object.values(graph.connections);
    const boq = generateNetworkBOQ(graph);

    const mdContent = `# Engineering Design Specification: ${currentProjectName || 'System Blueprint'}

**Design ID:** \`${graph.designId}\`  
**Revision:** \`${graph.metadata?.version || '1.0'}\`  
**Generated Date:** ${new Date().toISOString()}  
**Lead Engineer:** ${graph.metadata?.author || 'Principal Infrastructure Architect'}  

---

## 1. Architectural Overview
This document specifies the complete physical and logical design for **${currentProjectName}**, comprising **${nodes.length} equipment components** and **${connections.length} structured cable/pipe runs**.

### Equipment Inventory
| Tag | Device Name | Domain | Type | IP / Specs | Power (W) |
|---|---|---|---|---|---|
${nodes.map(n => `| **${n.tag}** | ${n.name} | ${n.domain} | \`${n.type}\` | ${n.properties.ipAddress || n.properties.voltage || 'N/A'} | ${n.properties.ratedWatts || 0}W |`).join('\n')}

---

## 2. Structured Cabling & Interconnect Schedule
| Run ID | Media Type | From Device (Port) | To Device (Port) | Length | Bandwidth |
|---|---|---|---|---|---|
${connections.map(c => `| \`${c.id}\` | **${c.connectionType}** | ${graph.nodes[c.sourceComponentId]?.tag || c.sourceComponentId} (${c.sourcePortId}) | ${graph.nodes[c.targetComponentId]?.tag || c.targetComponentId} (${c.targetPortId}) | ${c.lengthMeters}m | ${c.properties.bandwidthLimitMbps || 1000} Mbps |`).join('\n')}

---

## 3. Bill of Quantities (BOQ)
- **Total Material Cost:** $${boq.totalMaterials.toLocaleString()}
- **Total Installation Labor:** $${boq.totalLabour.toLocaleString()}
- **Tax (15%):** $${boq.taxAmount.toLocaleString()}
- **Grand Estimated Capital Expenditure:** **$${boq.grandTotal.toLocaleString('en-US', { minimumFractionDigits: 2 })}**

*Generated via NexFlow Enterprise Engineering Platform.*
`;

    if (download) {
      downloadFile(`${graph.designId || 'design'}_Specification.md`, mdContent, 'text/markdown');
    } else {
      copyToClipboard(mdContent, 'Markdown Specification');
    }
  };

  return (
    <Modal
      title={
        <Space>
          <ExportOutlined style={{ color: '#0284c7', fontSize: 18 }} />
          <span style={{ fontWeight: 700, fontSize: 16 }}>Multi-Format Engineering Export Suite</span>
        </Space>
      }
      open={isExportCenterModalOpen}
      onCancel={closeExportCenterModal}
      width={860}
      footer={[
        <Button key="close" onClick={closeExportCenterModal}>
          Close
        </Button>
      ]}
      style={{ top: 30 }}
    >
      <div style={{ color: '#f8fafc', padding: '6px 0' }}>
        <Paragraph style={{ color: '#94a3b8', fontSize: 13, marginBottom: 16 }}>
          Export the active engineering model into industry-standard interchange formats for CAD systems, procurement spreadsheets, documentation, or automated CI/CD pipeline validation.
        </Paragraph>

        <Row gutter={[16, 16]}>
          {/* Format 1: Canonical Engineering JSON */}
          <Col span={12}>
            <Card 
              size="small" 
              title={<Space><CodeOutlined style={{ color: '#38bdf8' }} /><span style={{ color: '#f8fafc' }}>Canonical Engineering Graph JSON</span></Space>}
              extra={<Tag color="#0284c7">RFC 8259</Tag>}
              style={{ backgroundColor: '#090d16', borderColor: '#1e293b' }}
            >
              <Paragraph style={{ color: '#cbd5e1', fontSize: 12, minHeight: 48, margin: 0 }}>
                Complete structured model with nodes, typed ports, geometric positions, domain properties, constraints, and telemetry bindings.
              </Paragraph>
              <div style={{ marginTop: 12, display: 'flex', gap: 8 }}>
                <Button size="small" icon={<DownloadOutlined />} type="primary" onClick={() => handleExportJson(true)} style={{ backgroundColor: '#0284c7' }}>
                  Download .json
                </Button>
                <Button size="small" icon={<CopyOutlined />} onClick={() => handleExportJson(false)}>
                  Copy JSON
                </Button>
              </div>
            </Card>
          </Col>

          {/* Format 2: Vector SVG Schematic */}
          <Col span={12}>
            <Card 
              size="small" 
              title={<Space><PictureOutlined style={{ color: '#10b981' }} /><span style={{ color: '#f8fafc' }}>Vector SVG Schematic Diagram</span></Space>}
              extra={<Tag color="#10b981">Vector Graphics</Tag>}
              style={{ backgroundColor: '#090d16', borderColor: '#1e293b' }}
            >
              <Paragraph style={{ color: '#cbd5e1', fontSize: 12, minHeight: 48, margin: 0 }}>
                Resolution-independent vector schematic with component chassis cards, port pinouts, and curved bezier cable runs ready for publication.
              </Paragraph>
              <div style={{ marginTop: 12, display: 'flex', gap: 8 }}>
                <Button size="small" icon={<DownloadOutlined />} type="primary" onClick={() => handleExportSVG(true)} style={{ backgroundColor: '#10b981' }}>
                  Download .svg
                </Button>
                <Button size="small" icon={<CopyOutlined />} onClick={() => handleExportSVG(false)}>
                  Copy SVG
                </Button>
              </div>
            </Card>
          </Col>

          {/* Format 3: BOQ Equipment Cost Schedule CSV */}
          <Col span={12}>
            <Card 
              size="small" 
              title={<Space><FileExcelOutlined style={{ color: '#eab308' }} /><span style={{ color: '#f8fafc' }}>Bill of Quantities (BOQ) Spreadsheet</span></Space>}
              extra={<Tag color="#eab308">Excel / CSV</Tag>}
              style={{ backgroundColor: '#090d16', borderColor: '#1e293b' }}
            >
              <Paragraph style={{ color: '#cbd5e1', fontSize: 12, minHeight: 48, margin: 0 }}>
                Structured CSV table with itemized hardware part numbers, quantities, material costs, labor rates, and total capital expenditure.
              </Paragraph>
              <div style={{ marginTop: 12, display: 'flex', gap: 8 }}>
                <Button size="small" icon={<DownloadOutlined />} type="primary" onClick={() => handleExportBOQ(true)} style={{ backgroundColor: '#eab308' }}>
                  Download BOQ.csv
                </Button>
                <Button size="small" icon={<CopyOutlined />} onClick={() => handleExportBOQ(false)}>
                  Copy CSV
                </Button>
              </div>
            </Card>
          </Col>

          {/* Format 4: Structured Cabling Run Schedule CSV */}
          <Col span={12}>
            <Card 
              size="small" 
              title={<Space><BuildOutlined style={{ color: '#06b6d4' }} /><span style={{ color: '#f8fafc' }}>Cabling & Patch Schedule</span></Space>}
              extra={<Tag color="#06b6d4">Installer Schedule</Tag>}
              style={{ backgroundColor: '#090d16', borderColor: '#1e293b' }}
            >
              <Paragraph style={{ color: '#cbd5e1', fontSize: 12, minHeight: 48, margin: 0 }}>
                Field installation schedule detailing point-to-point terminations, media categories (CAT6A, Fiber, 400V), lengths, and port IDs.
              </Paragraph>
              <div style={{ marginTop: 12, display: 'flex', gap: 8 }}>
                <Button size="small" icon={<DownloadOutlined />} type="primary" onClick={() => handleExportCableSchedule(true)} style={{ backgroundColor: '#06b6d4' }}>
                  Download CableSchedule.csv
                </Button>
                <Button size="small" icon={<CopyOutlined />} onClick={() => handleExportCableSchedule(false)}>
                  Copy CSV
                </Button>
              </div>
            </Card>
          </Col>

          {/* Format 5: Technical Specification Markdown */}
          <Col span={24}>
            <Card 
              size="small" 
              title={<Space><FileTextOutlined style={{ color: '#a855f7' }} /><span style={{ color: '#f8fafc' }}>Technical Specification Document (Markdown)</span></Space>}
              extra={<Tag color="#a855f7">Documentation</Tag>}
              style={{ backgroundColor: '#090d16', borderColor: '#1e293b' }}
            >
              <Paragraph style={{ color: '#cbd5e1', fontSize: 12, margin: 0 }}>
                Standard GitHub-compatible Markdown document containing the complete system specification, equipment inventory tables, cabling run matrix, and cost summaries for repository documentation or wiki pages.
              </Paragraph>
              <div style={{ marginTop: 12, display: 'flex', gap: 8 }}>
                <Button size="small" icon={<DownloadOutlined />} type="primary" onClick={() => handleExportMarkdown(true)} style={{ backgroundColor: '#a855f7' }}>
                  Download Spec.md
                </Button>
                <Button size="small" icon={<CopyOutlined />} onClick={() => handleExportMarkdown(false)}>
                  Copy Markdown
                </Button>
              </div>
            </Card>
          </Col>
        </Row>
      </div>
    </Modal>
  );
};
